Add CLI arguments and update spec
NovatecConsulting/fastlane-plugin-xcodegen pull request #2
Opened 2020-06-04 18:10 UTC by jcolicchio

This PR adds support for the following command line arguments:
`--quiet`
`--use-cache`
`--cache-path`

2020-06-04 18:12 UTC, jcolicchio commented
@m-ruhl I understand this repo is two years old but if you're still active please review, hopefully merge and release a version 0.2.0 of your plugin 🤞

2020-06-05 09:17 UTC, m-ruhl requested changes
Hi @jcolicchio,
Thanks for the PR. I found only a couple of suggestions..

2020-06-05 09:17 UTC, m-ruhl commented on lib/fastlane/plugin/xcodegen/actions/xcodegen_action.rb
> +                                      env_name: "XCODEGEN_PROJECT",
You should change the copied env_name

2020-06-05 09:17 UTC, m-ruhl commented on lib/fastlane/plugin/xcodegen/actions/xcodegen_action.rb
> +                                      env_name: "XCODEGEN_PROJECT",
Also with the other 2 params

2020-06-05 14:49 UTC, jcolicchio commented
@m-ruhl Done! How does this look? Also, appreciate the quick response :)

2020-06-15 07:53 UTC, m-ruhl approved these changes

2020-06-15 07:53 UTC, merged